# Imports

In [1]:
import pandas as pd
import numpy as np
import pickle

# Loading results

In [2]:
with open(r"C:\Users\mjnst\Desktop\results\run1\run_1.txt", 'rb') as f:
    r1 = pickle.load(f)
    
with open(r"C:\Users\mjnst\Desktop\results\run2\run_2.txt", 'rb') as f:
    r2 = pickle.load(f)
    
with open(r"C:\Users\mjnst\Desktop\results\run3\run_3.txt", 'rb') as f:
    r3 = pickle.load(f)

In [9]:
test_dict = {}

def get_results(file):
    for result in file:
        if result[0] not in test_dict:
            test_dict[result[0]] = [result[1][1]]
        else:
            test_dict[result[0]].append(result[1][1])

get_results(r1)
get_results(r2)
get_results(r3)

results = {i:np.nanmean(test_dict[i], axis=0) for i in test_dict}

results


{'Location 1 - flow': array([ 28.77244934,  28.66394107,  18.22614098,  19.3696579 ,
        125.64778837,  80.7446537 ]),
 'Location 2 - consumption': array([  0.61347382,   0.63454889,   0.33330154,   0.38291321,
         78.78706305, 126.90697632]),
 'Location 3 - consumption': array([4.73948822e-01, 5.44818382e-01, 2.89137721e-01, 3.52765882e-01,
        4.05901998e+02, 1.89154591e+03]),
 'Location 4 - consumption': array([ 0.45814624,  0.97126356,  0.26229765,  0.54871468,  7.80891116,
        19.4390254 ]),
 'Location 5 - consumption': array([2.24236895e-01, 2.98987647e-01, 1.49899303e-01, 2.23540202e-01,
        4.34458025e+05, 1.95475833e+06]),
 'Location 6 - head': array([0.77363958, 0.60472357, 0.40589834, 0.3380315 , 0.48599382,
        0.39385324]),
 'Location 7 - head': array([1.68786897, 1.72022326, 1.14741611, 1.17615469, 1.55375315,
        1.57502165]),
 'Location 8 - flow': array([ 28.85804428,  28.01207179,  21.5721768 ,  21.0410984 ,
        586.15279497, 100.725276

In [10]:
df = pd.DataFrame(results).T
df.columns = ["Train RMSE", "Test RMSE", "Train MAE", "Test MAE", "Train MAPE", "Test MAPE"]
df.index.name = "Location"
cols = pd.MultiIndex.from_product([['Train', 'Test'], ['RMSE', 'MAE', 'MAPE']])
df.columns = cols
df.sort_index(inplace=True)
df = df.astype(float).round(3)
df

Train                    Test               
                            RMSE     MAE    MAPE    RMSE         MAE   
Location                                                               
Location 1 - flow         28.772  28.664  18.226  19.370     125.648  \
Location 10 - flow        24.000  24.767  14.296  14.891    2094.733   
Location 11 - flow         5.745   1.130   3.801   0.446     741.154   
Location 11 - head         1.415   1.129   0.961   0.676       1.797   
Location 12 - head         2.289   1.795   1.261   1.106       1.988   
Location 2 - consumption   0.613   0.635   0.333   0.383      78.787   
Location 3 - consumption   0.474   0.545   0.289   0.353     405.902   
Location 4 - consumption   0.458   0.971   0.262   0.549       7.809   
Location 5 - consumption   0.224   0.299   0.150   0.224  434458.025   
Location 6 - head          0.774   0.605   0.406   0.338       0.486   
Location 7 - head          1.688   1.720   1.147   1.176       1.554   
Location 8 - flow         28.858  28.012  21.572  21.041     586.153   
Location 9 - head          0.196   0.134   0.124   0.081       0.225   

                                       
                                 MAPE  
Location                               
Location 1 - flow              80.745  
Location 10 - flow           2038.685  
Location 11 - flow            876.811  
Location 11 - head              1.244  
Location 12 - head              1.631  
Location 2 - consumption      126.907  
Location 3 - consumption     1891.546  
Location 4 - consumption       19.439  
Location 5 - consumption  1954758.333  
Location 6 - head               0.394  
Location 7 - head               1.575  
Location 8 - flow             100.725  
Location 9 - head               0.149

In [6]:
print(df.to_latex())

\begin{tabular}{lrrrrrr}
\toprule
 & \multicolumn{3}{r}{Train} & \multicolumn{3}{r}{Test} \\
 & RMSE & MAE & MAPE & RMSE & MAE & MAPE \\
Location &  &  &  &  &  &  \\
\midrule
Location 1 - flow & 28.772000 & 28.664000 & 18.226000 & 19.370000 & 125.648000 & 80.745000 \\
Location 10 - flow & 24.000000 & 24.767000 & 14.296000 & 14.891000 & 2094.733000 & 2038.685000 \\
Location 11 - flow & 5.745000 & 1.130000 & 3.801000 & 0.446000 & 741.154000 & 876.811000 \\
Location 11 - head & 1.415000 & 1.129000 & 0.961000 & 0.676000 & 1.797000 & 1.244000 \\
Location 12 - head & 2.289000 & 1.795000 & 1.261000 & 1.106000 & 1.988000 & 1.631000 \\
Location 2 - consumption & 0.613000 & 0.635000 & 0.333000 & 0.383000 & 78.787000 & 126.907000 \\
Location 3 - consumption & 0.474000 & 0.545000 & 0.289000 & 0.353000 & 405.902000 & 1891.546000 \\
Location 4 - consumption & 0.458000 & 0.971000 & 0.262000 & 0.549000 & 7.809000 & 19.439000 \\
Location 5 - consumption & 0.224000 & 0.299000 & 0.150000 & 0.224000 & 43

# Cluster stability

In [62]:
import os
from collections import Counter

In [12]:
directory = r"C:\Users\mjnst\Desktop\results"

In [34]:
[os.path.join(directory, run) for run in os.listdir(directory)]

['C:\\Users\\mjnst\\Desktop\\results\\run1',
 'C:\\Users\\mjnst\\Desktop\\results\\run2',
 'C:\\Users\\mjnst\\Desktop\\results\\run3']

In [56]:
clusters = [4, 4, 3, 3, 4, 4, 4, 3, 3, 4, 3, 4, 4]

In [70]:
for cluster, ru1, ru2, ru3 in zip(clusters, os.listdir("C:\\Users\\mjnst\\Desktop\\results\\run1"), os.listdir("C:\\Users\\mjnst\\Desktop\\results\\run2"), os.listdir("C:\\Users\\mjnst\\Desktop\\results\\run3")):
    with open("C:\\Users\\mjnst\\Desktop\\results\\run1\\" + ru1, 'rb') as f:
        ru1_indices = pickle.load(f)[0]

    with open("C:\\Users\\mjnst\\Desktop\\results\\run2\\" + ru2, 'rb') as f:
        ru2_indices = pickle.load(f)[0]
    
    with open("C:\\Users\\mjnst\\Desktop\\results\\run3\\" + ru3, 'rb') as f:
        ru3_indices = pickle.load(f)[0]

    # for i in range(cluster):
    # print(Counter(ru1_indices))
    # print(Counter(ru2_indices))
    # print(Counter(ru3_indices))

    print(np.unique(ru3_indices), np.unique(ru2_indices), np.unique(ru1_indices))
    # for a,b,c in zip(ru1_indices, ru2_indices, ru3_indices):
    #     if 
    # break

[2 3] [0 2] [0 2]
[1 3] [0 1 3] [1 2 3]
[0 2] [0 2] [0 2]
[0 1 2] [0 2] [1]
[0 2 3] [1 3] [0 2 3]
[1 2] [1 2 3] [1 2]
[0 1] [0 1] [0 1]
[0 1] [1 2] [1 2]
[0 3] [0 3] [0 3]
[0 3] [1] [1]
[1 3] [1 2 3] [1 2]
[0 1 2] [0 1 2] [0]
[0 2] [0 2] [1 2]


In [43]:
with open(r"C:\Users\mjnst\Desktop\results\run1\indices_run1_Location 1 - flow.txt", 'rb') as f:
    ru1_indices = pickle.load(f)
print(ru1_indices)

[array([0, 0, 0, ..., 2, 2, 2], dtype=int64), array([2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
     

In [20]:
base_results = ['run_1.txt', 'run_2.txt', 'run_3.txt']
for run in os.listdir(directory):
    f = os.path.join(directory, run)

    for run_result in os.listdir(f):
        if run_result not in base_results:
            print(run_result) 


indices_run1_Location 1 - flow.txt
indices_run1_Location 10 - flow.txt
indices_run1_Location 11 - flow.txt
indices_run1_Location 11 - head.txt
indices_run1_Location 12 - head.txt
indices_run1_Location 2 - consumption.txt
indices_run1_Location 3 - consumption.txt
indices_run1_Location 4 - consumption.txt
indices_run1_Location 5 - consumption.txt
indices_run1_Location 6 - head.txt
indices_run1_Location 7 - head.txt
indices_run1_Location 8 - flow.txt
indices_run1_Location 9 - head.txt
run_2_indices_Location 1 - flow.txt
run_2_indices_Location 10 - flow.txt
run_2_indices_Location 11 - flow.txt
run_2_indices_Location 11 - head.txt
run_2_indices_Location 12 - head.txt
run_2_indices_Location 2 - consumption.txt
run_2_indices_Location 3 - consumption.txt
run_2_indices_Location 4 - consumption.txt
run_2_indices_Location 5 - consumption.txt
run_2_indices_Location 6 - head.txt
run_2_indices_Location 7 - head.txt
run_2_indices_Location 8 - flow.txt
run_2_indices_Location 9 - head.txt
indices_run3_